# Robot configuration
robot_radius: 0.3  # Adjust based on your drone size
inflation_radius: 0.5
cost_scaling_factor: 3.0

# Observation sources
observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: lidar_link  # Adjust to your laser frame
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
  min_obstacle_height: -0.1  # For 2D, keep obstacles close to ground level
  max_obstacle_height: 3.0

# Plugin configuration
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
