ekf_localization_node:
  frequency: 50
  sensor_timeout: 0.1
  two_d_mode: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  publish_tf: true
  publish_acceleration: false
  # IMU config (7 booleans: x,y,z,pos/orient, angular_vel_z)
  imu0: /imu
  imu0_config: [false, false, false, false, false, true, true]
  imu0_differential: false
  imu0_remove_gravitational_acceleration: true
  imu0_queue_size: 10
  # GPS config (7 booleans: x,y,z,pos/orient, unused)
  gps0: /fix
  gps0_config: [true, true, false, false, false, false, false]
  gps0_differential: true
  gps0_queue_size: 10

  # Process and initial covariance (can use single values for simplicity)
  process_noise_covariance: [0.05,0,0,0,0,0,0,
                             0,0.05,0,0,0,0,0,
                             0,0,0.05,0,0,0,0,
                             0,0,0,0.05,0,0,0,
                             0,0,0,0,0.05,0,0,
                             0,0,0,0,0,0.05,0,
                             0,0,0,0,0,0,0.05]
  initial_estimate_covariance: [0.001,0,0,0,0,0,0,
                                0,0.001,0,0,0,0,0,
                                0,0,0.001,0,0,0,0,
                                0,0,0,0.001,0,0,0,
                                0,0,0,0,0.001,0,0,
                                0,0,0,0,0,0.001,0,
                                0,0,0,0,0,0,0.001]

