global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  
  width: 50.0  # Adjust based on your environment
  height: 50.0
  resolution: 0.05
  
  # Transform tolerance
  transform_tolerance: 0.2
  
  # Static layer
  static_layer:
    map_topic: /map
    subscribe_to_updates: true
