base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

planner_frequency: 1.0
planner_patience: 5.0
controller_frequency: 10.0
controller_patience: 15.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: false  # Set to false for drone
